### PR TITLE
Update ipv4_list.txt

### PR DESCRIPTION
**Pull request by kailashjoshi2005**

### CODE REVIEW

**Review by kailashjoshi2005 — COMMENTED** [review]
Added 172.217.170.174

**Comment by touhidurrr** [comment]
Do you have any ways for me to verify whether this IP is used by YouTube or not? Round Robin DNS makes a little difficult to verify it.

**Comment by kailashjoshi2005** [comment]
Hi,

 

Please see the attachment.

**Comment by touhidurrr** [comment]
@kailashjoshi2005 GitHub emails does not support attachments as far as I can see. Kindly reply via GitHub and not via email.

**Comment by touhidurrr** [comment]
Closing this because of inadequate response by the author. Also, the pr is not properly formatted.

**Pull request closed without merging**
